### ISSUE TITLE
Not actually an Issue, related to Font

### ISSUE THREAD

**Issue by ItsAnkan** [wildcraft958/MASK-W23-Animesh-23IE10004#1]
Hello Animesh, I heard from Soumil about your issue. (sorry for the delay)

To use a font you need to first import it using `@font-face` and then use the font by setting `font-family`.
I see that you have used the font-face Rule, so do the same again
```css
@font-face {
    font-family: 'Some Name';
    src: url('path-to-file');
    /* other properties */
}
```
After this you can use it in the quotes by setting `font-family` to 'Some name'.

![image](https://github.com/wildcraft958/MASK-W23-Animesh-23IE10004/assets/93087057/4b54358f-1805-4d98-8911-6cdb97607a5c)
